### ISSUE TITLE
Auto: Updating FTP autonomous

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#1]
Last year, we had an autonomous that parsed text files on the cRIO (that were sent via FTP, or File Transfer Protocol). You can view it in the 2012-Rebound-Rumble repository under the Team 2337 organization. We're going to need to port it over for Ultimate Ascent, so that way we can start planning and building possible autonomous routines.

**Comment by zpolygon95** [comment]
This feature has been implemented
