### ISSUE TITLE
Intake: Up & Down - In/ Off/ Out

### ISSUE THREAD

**Issue by cbolinger** [Team2337/2013-Ultimate-Ascent#10]
Create code to raise and lower the Intake System and have the ability to Take disk in and out (mainly for jams). Example would be the 2012 Robot.

We will also want to have some kind of sensor to tell when a disc has been picked up.

**Comment by szechy** [comment]
On the bunch of notecards in the back and through discussions with @silas13579 and Alex, we said we'd probably want to use the same eye sensors as in 2012 to track the discs. I think we were going to wait on publishing an issue like this until we had some sort of idea of what queueing system we were going to have (we can't write code for something that we can't even picture).

**Comment by Morgeno** [comment]
A few questions:

> What sort of sensors will be using for the intake?
> Is direction (up or down) of the frisbees important?
> Will there be a separate tank for the holding system or is the intake itself where they will be stored?
> How will they be moved to the shooter?
> If not covered in sensor question:  What are we doing to check how many frisbees are stored?

Clint:  At the feeder station, will the human player be throwing the discs onto the ground for our robot to grab, or can we make an adapted station intake?  I was thinking a hatch that slid open so discs could be dropped in quickly.  It seems like it would make it faster.

That's all that I can think of, if anyone can answer these or tell me anything I didn't ask, It would be appreciated.
Thanks

**Comment by szechy** [comment]
Morgan,

We'll probably be using sensors similar to those on 2012-bot - I'll show them to you next meeting, but basically they're reflective ones like those on garage doors. If the disc breaks the beam... there's a disc there. As for all of the other questions.... frankly, I don't think mechanical has figured out a design quite yet. You could talk to Stephen and have him show you his over-the-bumper intake, but the tricky part of this program will be the logic for staging discs (once they are inside the robot and before they go into the shooter).,. which hasn't been figured out yet.

**Comment by Morgeno** [comment]
Show them to me whenever you get a chance, but I have a basic program plugged in.  The only thing that remains are the sensors.
Thanks

**Comment by zpolygon95** [comment]
I may be mistaken, but this issue seems to have been updated. On rolling the intake out, will there be a way to roll discs out of the shooter without shooting them (to clear a jam for example)? If so, how should that be handled? If not, how should shooter jams be cleared?

Thanks
Zachary Polikarpus

**Comment by zpolygon95** [comment]
This should have been closed long ago
