### ISSUE TITLE
Auto: Using a gyro

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#11]
For turns in autonomous, we will likely need to use a gyro to track the position the robot is facing. Then, you have some sort of feedback loop of of the gyro data to determine how much power to send to the motors (most likely, again, a PID/proportional-integral-derivative loop). 

The other thing is that tuning may be required to get the gyro to measure turns accurately. From what I understand, gyros are influenced by a lot of external factors. Teams will write code to try and get the gyro to compensate for its external factors - apparently, what stopped team 118 on Einstein was a routine trying to fix their gyro that entered an infinite loop :(. I think that a build season task somebody would be to tune the gyro, and write a good feedback/PID loop.

**Comment by zpolygon95** [comment]
We tested getting gyro input a few days ago; the implementation is up to you, autonomous section leader.
