### ISSUE TITLE
Drive not opening

### ISSUE THREAD

**Issue by Tavaru5** [Team2337/2013-Ultimate-Ascent#20]
I have tried to open, tried to open after reverting some changes, and deleted and recloned and then opened the drive branch, yet the project says the there is a corrupt file. I also noticed that poops was in there? I didn't have this problem before Collin recommitted, and I'm not sure what's up with it. If anyone could shine some light on it, that would be much appreciated.

**Comment by Tavaru5** [comment]
So there is this global robot project that all of the branches are supposed to be updated on that I was never told of and was never put as an issue and no one ever took the time to integrate it into either vision or drive, so those two branches are far behind, unless that's what was being done in drive that caused it to mess up. Either way, according to @zpolygon95 , the code will have to be manually merged in order for it to be used.

**Comment by Tavaru5** [comment]
*global variable set/updated robot project

**Comment by szechy** [comment]
Yeah, @silas13579, we'll have to merge all of the code manually to master. That should start happening this week.

Drive can probably have a pull request done tonight. As for the issue with the drive branch, I believe I corrupted the LV project file locally, and I believe I just made a fixed version. It'll be pushed as soon as I have Internet access and am not running the practice bot.
