### ISSUE TITLE
More Gifs

### ISSUE THREAD

**Issue by ZachOrr** [Team2337/2013-Ultimate-Ascent#21]
When you guys do pull requests you should make little videos (and make them gifs) to show the functionality working. It saves time for people reviewing your code, will be good to show functionality when you open source the code, and gives Clint (and secretly me) something to look at.

5 days left to build. Godspeed.

**Comment by zpolygon95** [comment]
@ZachOrr Can you recommend software to do this?

**Comment by ZachOrr** [comment]
Mmmmmm no. I wrote my own iPhone app to do it, and if I wanted to do it on my computer I'd write a little Python to do it.

Maybe check for an online service that'll turn video into a gif? That'd be my suggestion.

**Comment by zpolygon95** [comment]
Ok. Do you mean videos of the robot or videos of the code running and spitting out values? Probably the robot.

**Comment by ZachOrr** [comment]
For sure the robot.

**Comment by szechy** [comment]
We would probably want to use [Gifboom](http://gifboom.com/)  because it's multiplatform. Something to look into today.
