### ISSUE TITLE
Global Variables

### ISSUE THREAD

**Issue by zpolygon95** [Team2337/2013-Ultimate-Ascent#25]
The internal variables library seems to be overflowing with duplicate and unused variables after the two most recent merges. I need anyone who created global variables for their code to comment and tell me exactly the names of the variables, their functions, and the VIs that they are used in. I want this information in comments so that I have a record while I am merging the code.

@AlexNaegle @Carlcamp @ColinSz @DGriyu @Morgeno

Thanks!
~Zachary Polikarpus

**Comment by zpolygon95** [comment]
I have two unused variables currently in the master branch: "shootPID" and "shootDirectInput". These seem like variables that belong in the shooter branch (which has yet to be merged). Neither of these variables have descriptions.

**Comment by szechy** [comment]
I'm having troubles editing my interval variables so I could push up a new copy, but here's the ones in the auto branch. There is a LOT of crossover between other branches, I imagine, so we can simplify that way. I believe mine all follow the proper naming standards.
- armPosition - would be the reading from the arm's string pot.
- autoNumber - determines which auto text file to look at
- autoTimeDelay - the wait in autoMain, defined in Begin.vi
- driveLeft - the motor power to send to the left drive motors (should work across all robot modes - auto, teleop, test, then write zeroes in drive)
- driveRight - ^^^
- intakePosition - a boolean, the command to the solenoid controlling the intake. May need to be changed to an enum to deal with the double solenoid better - looking for @zpolygon95's advice here.
- intakePower - Mechanical has wanted to play around with this for whatever reason, but I see it going away soon. Not [deprecated](http://en.wikipedia.org/wiki/Deprecation), but perhaps close.
- shifter - like intakePosition, the command to the shifter solenoid. I'm guessing this is OK as a boolean, and not a solenoid enum.
- shooterRPM - the current goal shooter RPM (should be accessible across all modes too

While I haven't looked personally, I have a feeling that these are the majority of everyone else's variables, except with the shooter branch's. I believe that @DGriyu has implemented dynamic switching of algorithms to run the shooter, hence the odd internal variables - you'll have to talk to him about that.

**Comment by szechy** [comment]
I think we've resolved the internal variables confusion - trailblaze away, gentlemen!
