### ISSUE TITLE
test-mode?

### ISSUE THREAD

**Issue by zpolygon95** [Team2337/2013-Ultimate-Ascent#3]
@ColinSz what is the intended purpose of the "test-mode" branch? It is not quite apparent from the name. What are we testing?

**Comment by ZachOrr** [comment]
Clint talked about test mode just before the season started. It's to test all the systems of the robot without having it touch the floor. It's meant to do once we get back to the pits after matches (or before matches). Basically to ensure all the systems work properly.

The hope is that you'd be able to do it from the dashboard, IIRC

**Comment by zpolygon95** [comment]
Oh that. I wasn't aware we were calling it "test-mode". Thanks for clarifying

**Comment by szechy** [comment]
Yeah, this also has to do with the new "Test" operating mode in the Driver Station (alongside Autonomous and Teleoperated). If you remember, we saw it at the 1718 Beta Test event. I expect all of our "test-mode" related code will be plopped in that branch.
