### ISSUE TITLE
Drive: Cheesy Drive

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#4]
We are going to implement a version of Cheesy Drive from scratch (as opposed to using FRC33's last year) because we have enough people to do that sort of thing; plus, while we're looking at it, maybe people will come up with new ideas to improve it. Currently, @silas13579 is on it.

**Comment by szechy** [comment]
I think the next step, once we have a working driveCheesy, is to try it out in the new robot simulator packaged with LabVIEW. It will be interesting to see if the simulator will be useful and light enough on processing to run, and I think this is the application it is primarily designed for (drivetrain code).

**Comment by Tavaru5** [comment]
The simulator didn't work for me/my code, but we have instituted Cheesy Drive and ramping on the 2012 bot and they are functional so far.

**Comment by szechy** [comment]
s of right now, I see us with a chassis ready for testing on Sunday. @silas13578 and @AlexNaegle, the first code to test will be yours! Be ready and prepared to take a break from vision.

**Comment by Tavaru5** [comment]
Well so far the drive seems to be working. Other than the backwards turning bug that randomly appeared and was randomly fixed, the code should be functional. @ColinSz  and @AlexNaegle  unless either of you have objections, maybe close this issue?
