### ISSUE TITLE
Shooter: Speed control

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#5]
If we are to go with a shooter this year (mechanical hasn't determined what they want to do yet), then we are going to need some form of speed control for the shooter wheels. 

Last year, we simply had one magnetic proximity sensor that counted once each cycle, using the Counter class from WPILib (which is the formal name for the FRC palette/grouping of VI's). 

I think we'd do the same again, but what sort of programming should we use on our "feedback" loop (where we take the data from the sensor and do something with it?

As I see it, our options are currently:
- PID control (Proportional-Integral-Derivative, read [this](http://www.chiefdelphi.com/media/papers/1823) for more information. This is what we did last year, and it ended up working fairly well.
- Bang-bang control - read [this](http://www.chiefdelphi.com/media/papers/2663) for more information. Essentially, if your robot is below your target speed/RPM, then you give it 100%. If it's above, you don't give it any power.
- Anyone else have any other ideas?

**Comment by cbolinger** [comment]
I would prefer us to use PID similar to last year. Also we will need to have two separate PIDs, one for each barrel, if we have two shooters.

**Comment by szechy** [comment]
Why do you prefer PID? I've been thinking about these two methods for a while now, and I think it's worth experimenting with bang-bang.

I think we'd need to have just two separate PID loops, but with the same tuning parameters (that is, constants for the proportional, integral, and derivative terms). They just need to run separately in case each barrel fires slightly off time-wise compared to the other.

**Comment by zpolygon95** [comment]
This feature has been implemented extremely well by @DGriyu
