### ISSUE TITLE
Config-File: Create and use a config file in a network.

### ISSUE THREAD

**Issue by szechy** [Team2337/2013-Ultimate-Ascent#6]
So here's the story behind the configuration file thing:

This year, we want to try to have a text file of configuration details on the robot, executed similarly to how we drop text files on the robot as auton plans. A configuration file would basically contain all of the constants and other variables that the robot uses (for instance, in driveCheesy, it would contain the constants for turning with some throttle and no throttle, in both gears - total of 4 constants).

So here's how I picture it getting executed:
- You have a subVI that accesses the text file using LabVIEW File I/O and unpacks it, and then writes each line (which is a separate constant) to our robot's NetworkTable.
- When you parse the text file, you allow for comments - such as to state what each line's constant is for. Perhaps, you even have the parsing look for a string to name each variable in the NetworkTable.
- By placing all of the constants in the NetworkTable, you can edit and tune them - probably in just Test mode.
- When you need a constant from the NetworkTable, just look it up from the NetworkTable.
- You write a subVI that works in Test mode (or Disabled mode, or maybe both) that allows you to save the current NetworkTable into a new config file (and takes the config file that the robot booted up with, and saves it under a different name in case we need to restore that).

Does anybody have any suggestions? I'm also looking for volunteers to pick up parts of these bullet points - if you do so, we'll probably form a new issue on your task.

**Comment by zpolygon95** [comment]
Just a note, git gives Morgan credit for the last commit in the config-file branch, but Marl was the one who pushed it. As a clarification, Carl was the one who worked on this code and git for windows mis-credited the commit. I believe this can be avoided in the future if everyone has a dedicated machine to ship code from. But on the other hand, this is not a very important issue in comparison to shipping the code itself

**Comment by DGriyu** [comment]
@zpolygon95 Yeah, Silas was having this problem earlier as well. If you go into tools and then options you have to make sure git is configured to your name and email as well as being logged onto your account
![pic](https://f.cloud.github.com/assets/1393227/88789/59bb0a08-6503-11e2-897f-bb4c3cd5dfb4.png)

**Comment by Carlcamp** [comment]
Good to know thanks

**Comment by zpolygon95** [comment]
Has this been implemented in any branch?

**Comment by szechy** [comment]
Just had a couple of commits dealing with this file! Just needs to be tested and then it's a feature. Post new issues as ideas of constants to add!

**Comment by szechy** [comment]
Allow me to clarify - currently, this is a local config file stored on the cRIO. Later on, we should probably develop test-mode routines, and perhaps those could remotely access that file and reload the constants ONLY when you're in test-mode.

**Comment by Carlcamp** [comment]
Ok
